User permission and location display
DumitruBogdan/WeatherAPP pull request #1
Opened 2022-02-22 13:33 UTC by DumitruBogdan

In this branch, you can find the implementation of:
- requesting the user's permission for the location service
- displaying the geographical coordinates
- displaying the city name based on the determined coordinates

2022-02-22 13:37 UTC, vladstanescu94 requested changes

2022-02-22 13:37 UTC, vladstanescu94 commented on WeatherAPP/WeatherAPP/Features/Weather/View/WeatherView.swift
> +import CoreLocation
We don't need this import here

2022-02-22 13:37 UTC, vladstanescu94 commented on WeatherAPP/WeatherAPP/Util/ViewController.swift
> +
We don't need this file anymore

2022-02-22 13:41 UTC, DumitruBogdan commented on WeatherAPP/WeatherAPP/Util/ViewController.swift
> +
Resolved

2022-02-22 13:41 UTC, DumitruBogdan commented on WeatherAPP/WeatherAPP/Features/Weather/View/WeatherView.swift
> +import CoreLocation
Resolved

2022-02-22 13:41 UTC, vladstanescu94 approved these changes

2022-02-23 11:19 UTC, mihaigpm approved these changes

2022-02-23 11:19 UTC, merged